function [ w, gamma0, output ] = set_gamma0( M )

% 设置初始 gamma0 值
a = M.p ;
b = M.q ;
n = size( M.p, 1 ) ;

options = optimoptions( 'fmincon'  , ...
                        'Display'  ,'none', ...
                        'Algorithm','interior-point' ) ;

[ x        , ...
  fval     , ...
  exitflag , ...
  output  ] = fmincon( @(x) -f_obj(x) ,      ...
                          3*ones( n, 1 ),      ...
                          []            , [] , ...
                          []            , [] , ...
                          a             , b  , ...
                          [], ...
                          options ) ;

w               = x        ;
gamma0          = -fval    ;
output.exitflag = exitflag ;

end